### ISSUE TITLE
What should be a (weak)dep?

### ISSUE THREAD

**Issue by mrufsvold** [cjdoris/PandasIO.jl#1]
This is a project I've been thinking about for a long time. Glad to see you're kicking it off! I'd love to contribute some methods, but I had a question before doing anything.

I noticed that you have JSON3 and Gumbo in your Deps. Once you have methods for `read_` / `to_` CSV, Excel, parquet, etc., it's going to be a pretty long list of dependencies.

Do you intend for the package to come batteries included, or should the user get to add just the dependencies for the methods they want?

**Comment by cjdoris** [comment]
I think I'm actually going to rename this package to PandasJSON and only handle the Pandas JSON format. There are plenty of other packages which already do table I/O for other formats that Pandas uses (CSV, Parquet, Excel, ...). If you want to tackle any other formats or make a PandasIO meta-package which brings them all together, be my guest!

**Comment by cjdoris** [comment]
The Gumbo stuff was just a couple of hours hacking around parsing HTML tables - I'm going to delete it.

**Comment by mrufsvold** [comment]
Okay! Sounds like a plan. I do think a meta-package would be nice for people coming from Python who could use a guide figuring out which packages can help with all the formats.
